### ISSUE TITLE
React & Inline CSS; a match made in heaven?

### ISSUE THREAD

**Issue by cdownard** [Denver-Devs/reactjs-denver#4]
Many React devs have started writing inline styles rather than separating their concerns based on file types. We’ll talk about why that is and isn’t a good idea, and look at some examples of inline styling with React. We’ll also spend some time looking at an alternative approach. This talk is an evolution of a talk given at Develop Denver. If you attended that talk, you may want to check your twitter feed for the first 2/3rd’s of the talk until I start to cover new ground.

**Comment by DrewDahlman** [comment]
I like this concept
